### ISSUE TITLE
Error in SQL syntax

### ISSUE THREAD

**Issue by PhilharmonieLeende** [magnushasselquist/hqcblistmailer#1]
For testing purpose I have created in CB 2.0.14 a mailing list which only includes my own account. Then I made an e-mail template successfully. When I go to the sent mail tab I immediately receive the error message below:

 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"sort_mode":"0","sort_basic":[{"column":"name","direction":"ASC"}],"sort_advance' at line 1 SQL=select \* from j25_users inner join j25_comprofiler on j25_users.id = j25_comprofiler.user_id where j25_users.block = 0 having {"sort_mode":"0","sort_basic":[{"column":"name","direction":"ASC"}],"sort_advanced":"","filter_mode":"0","filter_basic":[{"column":"name","operator":"LIKE","value":"Mark"}],"filter_advanced":"","columns":[{"title":"email","size":"3","cssclass":"","fields":[{"field":"50","display":"4"}]}],"list_search":"1","list_search_fields":"","list_compare_types":"0","list_search_empty":"0","list_search_collapse":"0","list_show_selector":"1","list_show_blocked":"0","list_show_banned":"1","list_show_unapproved":"0","list_show_unconfirmed":"0","list_grid_layout":"0","list_grid_height":"200","list_grid_width":"200","list_limit":"30","list_paging":"1","allow_profilelink":"1","hotlink_protection":"0"}name LIKE 'Mark'

The only option I have is to return to the control panel.

ps I highly aprreciate the functionality you are adding. It seems exactly what I have been searching for for a long time. So I hope this is easy to fix.

**Comment by magnushasselquist** [comment]
Hi!

Tanks for your email! I will look into this and try to solve it! What do
you have on the filter tab for that list?

/Magnus

söndag 19 juni 2016 skrev PhilharmonieLeende <notifications@github.com>:

> For testing purpose I have created in CB 2.0.14 a mailing list which only
> includes my own account. Then I made an e-mail template successfully. When
> I go to the sent mail tab I immediately receive the error message below:
>
> 1064 You have an error in your SQL syntax; check the manual that
> corresponds to your MySQL server version for the right syntax to use near
> '"sort_mode":"0","sort_basic":[{"column":"name","direction":"ASC"}],"sort_advance'
> at line 1 SQL=select * from j25_users inner join j25_comprofiler on
> j25_users.id = j25_comprofiler.user_id where j25_users.block = 0 having
> {"sort_mode":"0","sort_basic":[{"column":"name","direction":"ASC"}],"sort_advanced":"","filter_mode":"0","filter_basic":[{"column":"name","operator":"LIKE","value":"Mark"}],"filter_advanced":"","columns":[{"title":"email","size":"3","cssclass":"","fields":[{"field":"50","display":"4"}]}],"list_search":"1","list_search_fields":"","list_compare_types":"0","list_search_empty":"0","list_search_collapse":"0","list_show_selector":"1","list_show_blocked":"0","list_show_banned":"1","list_show_unapproved":"0","list_show_unconfirmed":"0","list_grid_layout":"0","list_grid_height":"200","list_grid_width":"200","list_limit":"30","list_paging":"1","allow_profilelink":"1","hotlink_protection":"0"}name
> LIKE 'Mark'
>
> The only option I have is to return to the control panel.
>
> ps I highly aprreciate the functionality you are adding. It seems exactly
> what I have been searching for for a long time. So I hope this is easy to
> fix.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/magnushasselquist/hqcblistmailer/issues/1>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFIa9uOLjLMOUJZpLLPA7gtQLUrxmTLCks5qNPu_gaJpZM4I5HkC>
> .
>


-- 
Magnus Hasselquist
magnus.hasselquist@gmail.com

**Comment by PhilharmonieLeende** [comment]
The filter tab has 'basic' setting:
'name' 'contains' 'Mark'

**Comment by PhilharmonieLeende** [comment]
Hi,

I provided the filter tab info in the previous comment. Is that sufficiently clear? Os should I make a screen shot.

Thanks for your willingness to look in to this.

Mark

**Comment by magnushasselquist** [comment]
Hi,

Yes, that is sufficient.

As a workaround, while I am fixing the problem, please try to use the
Advanced filter option, and write:
name LIKE 'Mark'

/Magnus

2016-06-19 18:22 GMT+02:00 PhilharmonieLeende <notifications@github.com>:

> Hi,
>
> I provided the filter tab info in the previous comment. Is that
> sufficiently clear? Os should I make a screen shot.
>
> Thanks for your willingness to look in to this.
>
> Mark
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/magnushasselquist/hqcblistmailer/issues/1#issuecomment-227006064>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFIa9jCbvzQbJu2DP8XT7uDfrY77cwlVks5qNWzZgaJpZM4I5HkC>
> .
>



-- 
Magnus Hasselquist
magnus.hasselquist@gmail.com

**Comment by PhilharmonieLeende** [comment]
Dear Magnus,

Thank for you effort. I first tried the workaround. It turns up with 'No users in this list' (or something similar that, I had to translate it from Dutch) when I check it at the front-end. 

Then I tried to find version 1.0.7 which should be attached to your message. Unfortunately I am very new to GitHub and was not able to find it from your posting. Thereafter I assumed that it is the most recent version in the  <>code section, so I downloaded it from there. I now receive another error message:

 1146 Table 'philharm_joomla2.j25_comprofiler' doesn't exist SQL=select * from #__users inner join j25_comprofiler on j25_users.id = #__comprofiler.user_id where #__users.block = 0 having name LIKE 'Mark'

I would guess that "j25" should read "jos" for my site. 

Best regards,
Mark

**Comment by magnushasselquist** [comment]
Hi again,

My bad. Please see the new 1.0.8 version that fixes the issue with j25.
https://github.com/magnushasselquist/hqcblistmailer/releases/tag/v.1.0.8

/Magnus

2016-06-20 23:17 GMT+02:00 Webbeheer Koninklijke Fanfare Philharmonie
Leende <notifications@github.com>:

> Dear Magnus,
>
> Thank for you effort. I first tried the workaround. It turns up with 'No
> users in this list' (or something similar that, I had to translate it from
> Dutch) when I check it at the front-end.
>
> Then I tried to find version 1.0.7 which should be attached to your
> message. Unfortunately I am very new to GitHub and was not able to find it
> from your posting. Thereafter I assumed that it is the most recent version
> in the <>code section, so I downloaded it from there. I now receive another
> error message:
>
> 1146 Table 'philharm_joomla2.j25_comprofiler' doesn't exist SQL=select *
> from #__users inner join j25_comprofiler on j25_users.id =
> #__comprofiler.user_id where #__users.block = 0 having name LIKE 'Mark'
>
> I would guess that "j25" should read "jos" for my site.
>
> Best regards,
> Mark
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/magnushasselquist/hqcblistmailer/issues/1#issuecomment-227272231>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFIa9h5xeuMqVroRTBjcQ9NZ6GsoIb3Cks5qNwNVgaJpZM4I5HkC>
> .
>



-- 
Magnus Hasselquist
magnus.hasselquist@gmail.com

**Comment by PhilharmonieLeende** [comment]
Hi Magnus,

Yes, the SQL errors have gone! 
Now if I go to the 'Email sender' I can select my test template and then the preview is shown, but I am not able to actually send the message. Item 3 "Skicka" is not showing for this particular list.

In a further experiment a used a real mail-distribution list with 69 entries. In this case the third entry appeared: "3. Skicka" . There I can select to mail myself or to send to the actual list. After pressing send to myself I see: "OK till dig själv". The good news however is that I receive the mail sent out!

In addition I expected to be able to edit the subject and body text this preview mode. I am not sure if this is a bug or that you implemented as such intentionally. 

Recapitulating the new/remaining issues:
1) "3. Skicka" does not show when I select the list in which I am the only participant; 
2) "Skicka"and "OK till dig själv" are Swedish, while the rest is English;
3) I expected to be able to edit the "Subject" & "Body" from the send menu;

Further I have two feature requests. I am not sure if you have an interest in implementing them, if it is even feasible or that is straightforward. My apologies for my ignorance. 
The features are:
1) Module to send mail from the front end (limited to certain user groups);
2) Adding attachments form the mail, preferably of files which are stored locally on the users computer.

If you are interested I am willing to create Dutch language files, but then I need some guidance for you how to do this. 

Best regards,
Mark

**Comment by magnushasselquist** [comment]
Hi!

Sorry for not answering earlier. I need to look in to the cases 1 and 2.
For case 3, thanks for your suggestion. Currently that is part of the email
definition.
I am not sure my self on the language files, but maybe I should look in to
that :)

A module and File upload is great ideas. I will save that for a rainy day.

Firstly, I will look and respond on 1 and 2.

/Magnus



2016-06-21 12:32 GMT+02:00 Webbeheer Koninklijke Fanfare Philharmonie
Leende <notifications@github.com>:

> Hi Magnus,
>
> Yes, the SQL errors have gone!
> Now if I go to the 'Email sender' I can select my test template and then
> the preview is shown, but I am not able to actually send the message. Item
> 3 "Skicka" is not showing for this particular list.
>
> In a further experiment a used a real mail-distribution list with 69
> entries. In this case the third entry appeared: "3. Skicka" . There I can
> select to mail myself or to send to the actual list. After pressing send to
> myself I see: "OK till dig själv". The good news however is that I receive
> the mail sent out!
>
> In addition I expected to be able to edit the subject and body text this
> preview mode. I am not sure if this is a bug or that you implemented as
> such intentionally.
>
> Recapitulating the new/remaining issues:
> 1) "3. Skicka" does not show when I select the list in which I am the only
> participant;
> 2) "Skicka"and "OK till dig själv" are Swedish, while the rest is English;
> 3) I expected to be able to edit the "Subject" & "Body" from the send menu;
>
> Further I have two feature requests. I am not sure if you have an interest
> in implementing them, if it is even feasible or that is straightforward. My
> apologies for my ignorance.
> The features are:
> 1) Module to send mail from the front end (limited to certain user groups);
> 2) Adding attachments form the mail, preferably of files which are stored
> locally on the users computer.
>
> If you are interested I am willing to create Dutch language files, but
> then I need some guidance for you how to do this.
>
> Best regards,
> Mark
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/magnushasselquist/hqcblistmailer/issues/1#issuecomment-227402151>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFIa9hfN1rUyARM9sWQG_5xU91fqvZ4-ks5qN72_gaJpZM4I5HkC>
> .
>



-- 
Magnus Hasselquist
magnus.hasselquist@gmail.com

**Comment by PhilharmonieLeende** [comment]
Dear Magnus,

Thanks for your interest in looking in to this. I understand that you do
not always have time :-). For now our secretary is able to mail so there
is less urgency. 

Best regards,
Mark 

On 2016-06-30 16:20, Magnus Hasselquist wrote:

> Hi!
> 
> Sorry for not answering earlier. I need to look in to the cases 1 and 2.
> For case 3, thanks for your suggestion. Currently that is part of the email
> definition.
> I am not sure my self on the language files, but maybe I should look in to
> that :)
> 
> A module and File upload is great ideas. I will save that for a rainy day.
> 
> Firstly, I will look and respond on 1 and 2.
> 
> /Magnus
> 
> 2016-06-21 12:32 GMT+02:00 Webbeheer Koninklijke Fanfare Philharmonie
> Leende <notifications@github.com>:
> 
>> Hi Magnus,
>> 
>> Yes, the SQL errors have gone!
>> Now if I go to the 'Email sender' I can select my test template and then
>> the preview is shown, but I am not able to actually send the message. Item
>> 3 "Skicka" is not showing for this particular list.
>> 
>> In a further experiment a used a real mail-distribution list with 69
>> entries. In this case the third entry appeared: "3. Skicka" . There I can
>> select to mail myself or to send to the actual list. After pressing send to
>> myself I see: "OK till dig själv". The good news however is that I receive
>> the mail sent out!
>> 
>> In addition I expected to be able to edit the subject and body text this
>> preview mode. I am not sure if this is a bug or that you implemented as
>> such intentionally.
>> 
>> Recapitulating the new/remaining issues:
>> 1) "3. Skicka" does not show when I select the list in which I am the only
>> participant;
>> 2) "Skicka"and "OK till dig själv" are Swedish, while the rest is English;
>> 3) I expected to be able to edit the "Subject" & "Body" from the send menu;
>> 
>> Further I have two feature requests. I am not sure if you have an interest
>> in implementing them, if it is even feasible or that is straightforward. My
>> apologies for my ignorance.
>> The features are:
>> 1) Module to send mail from the front end (limited to certain user groups);
>> 2) Adding attachments form the mail, preferably of files which are stored
>> locally on the users computer.
>> 
>> If you are interested I am willing to create Dutch language files, but
>> then I need some guidance for you how to do this.
>> 
>> Best regards,
>> Mark
>> 
>> --
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/magnushasselquist/hqcblistmailer/issues/1#issuecomment-227402151>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AFIa9hfN1rUyARM9sWQG_5xU91fqvZ4-ks5qN72_gaJpZM4I5HkC>
>> .
>> 
> 
> -- 
> Magnus Hasselquist
> magnus.hasselquist@gmail.com 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 

Koninklijke Fanfare Philharmonie Leende 
Mark van Helvoort/Debby Postulart, webbeheer
Julianastraat 3 
5595 CM Leende 
http://www.philharmonieleende.nl 

 

Links:
------
[1]
https://github.com/magnushasselquist/hqcblistmailer/issues/1#issuecomment-229672639
[2]
https://github.com/notifications/unsubscribe/ATGMOzCqB-iui9dBkvu0VQ4ILH7XK_R5ks5qQ9CWgaJpZM4I5HkC

**Comment by magnushasselquist** [comment]
New version will work better with filter sql from simple filters.
